name: Release Package

on:
  push:
    branches: [release]

jobs:
  storybook-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: ./react-d3-chart
      - uses: actions/setup-node@master
        with:
          working-directory: ./react-d3-chart
      - name: Install Yarn
        working-directory: ./react-d3-chart
        run: |
          yarn install
      - name: Build Package
        working-directory: ./react-d3-chart
        run: |
          yarn build:lib
      - name: Release Package
        working-directory: ./react-d3-chart    
      - name: Yarn Package Publish
      uses: luvies/action-yarn-publish@v0.1.1
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

