name: Release Package

on:
  push:
    branches: [release]

jobs:
  storybook-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: ./react-d3-chart
      - uses: actions/setup-node@master
        with:
          working-directory: ./react-d3-chart
      - name: Install Yarn
        working-directory: ./react-d3-chart
        run: |
          yarn install
      - name: Build Package
        working-directory: ./react-d3-chart
        run: |
          yarn build:lib
      - name: Yarn Package Publish
        working-directory: ./react-d3-chart
        run: |
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
