name: Storybook Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  storybook-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: ./react-d3-chart
      - uses: actions/setup-node@master
        with:
          working-directory: ./react-d3-chart
      - name: Install Yarn
        working-directory: ./react-d3-chart
        run: |
          yarn install
      - name: Build Storybook
        working-directory: ./react-d3-chart
        run: |
          yarn build-storybook
      - name: Deploy Storybook
        working-directory: ./react-d3-chart
        run: |
          yarn deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
